Add support button
savoirfairelinux/standard-plus-addons pull request #1
Opened 2017-01-16 21:07 UTC by JulieSFL

2017-01-16 21:12 UTC, joaoalf commented on standard_plus_issue/__manifest__.py
> +    'application': True,
@JulieSFL Je ne pense pas que ce module se qualifie pour être une application.

2017-01-16 21:18 UTC, joaoalf commented on standard_plus_issue/__manifest__.py
> +    'application': True,
@JulieSFL Oublie mon dernier commentaire. On va considérer comme application.

2017-01-16 21:26 UTC, joaoalf requested changes
@JulieSFL 2 trucs:

Pourquoi l'image est dans `static/description` et pas dans `static/img`?
Peux-tu faire de façon que image soit utilisé aussi comme icon du module?

2017-01-16 21:31 UTC, JulieSFL commented
@joaoalf  L'image est toute petite (17x17px) donc je rajoute la même en plus grand pour l'icone du module?

2017-01-16 22:18 UTC, JulieSFL commented
@joaoalf J'ai mis le logo dans img et une autre image pour l'icone du module dans description

2017-01-17 22:17 UTC, joaoalf approved these changes
:+1:

2017-01-17 22:17 UTC, merged