[ADD] support mail in config view
savoirfairelinux/standard-plus-addons pull request #14
Opened 2018-01-08 23:20 UTC by ventilooo

WIP

2018-01-09 16:34 UTC, joaoalf requested changes
@ventilooo I don't see where in the code we tell the system to use the email in ir.config_parameter.

The file names don't correspond to the models.

2018-01-09 16:51 UTC, ventilooo commented
If you check the other module in odoo, like [this one](https://github.com/odoo/odoo/blob/10.0/addons/mail/models/res_config.py). The file name is `res_config.py` but the Class is `BaseConfiguration`

2018-01-11 17:25 UTC, ventilooo commented
@joaoalf fixed according to your review !

2018-01-11 19:37 UTC, rimbendhaou approved these changes
It's ok

2018-01-11 21:29 UTC, joaoalf requested changes
@ventilooo Voir mon commentaire pour la doc. Sinon, rebase + traductions.

2018-01-11 21:29 UTC, joaoalf commented on standard_plus_issue/README.rst
> +Replace 'support@support.com' in '/data/ir_config_parameter.xml' with
@ventilooo Ça ne fait pas du sens.

2018-01-12 18:48 UTC, joaoalf requested changes
@ventilooo You're not picking the address from the good place.

2018-01-12 18:48 UTC, joaoalf commented on standard_plus_issue/models/standard_plus_issue.py
> +                self.env['base.config.settings'].get_default_support_email(
@ventilooo ??

2018-01-12 19:55 UTC, ventilooo commented
@joaoalf review ;)

2018-01-12 22:37 UTC, joaoalf approved these changes

2018-01-12 22:37 UTC, merged