Improve form view for future inherited modules
savoirfairelinux/standard-plus-addons pull request #4
Opened 2017-02-10 22:20 UTC by JulieSFL

@joaoalf

2017-02-14 18:05 UTC, joaoalf requested changes

2017-02-14 18:05 UTC, joaoalf commented on standard_plus_issue/views/standard_plus_issue.xml
> +            <button name="action_set_escalated" type="object" string="Submit"
@JulieSFL Ce sont les autres modules qui doivent ajouter cette logique.

2017-02-16 21:02 UTC, JulieSFL commented
@joaoalf J'ai modifié pour qu'il n'y ait plus mention des modules studio et aeroo mais il reste quand même en place une logique qui est là pour le bon fonctionnement de leur héritage. Donc dis moi stp si c'est bon ou pas de laisser cette logique en place.

2017-02-16 23:25 UTC, joaoalf approved these changes

2017-02-16 23:25 UTC, merged